### ISSUE TITLE
Theano install of 1.0.1 causes downgrade of pygpu to 6.9

### ISSUE THREAD

**Issue by guptarajat** [conda-forge/theano-feedstock#18]
Theano 1.0.1 gives this error with pygpu 6.9

From default channels it seems to be working just fine.
`
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/usr/lib/a-4.2.0-py-3.5.3-dl-gpu-full/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 227, in <module>
    use(config.device)
  File "/usr/lib/a-4.2.0-py-3.5.3-dl-gpu-full/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "/usr/lib/a-4.2.0-py-3.5.3-dl-gpu-full/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 73, in init_dev
    pygpu_version.fullversion)
ValueError: Your installed version of pygpu(0.6.9) is too old, please upgrade to 0.7.0 or later (but below 0.8.0)
Using Theano backend.`

**Comment by jakirkham** [comment]
Good catch. Would you like to submit a quick PR to fix it?

**Comment by guptarajat** [comment]
I dont have much clue about conda-forge yet, but have given it a try https://github.com/conda-forge/theano-feedstock/pull/19

Will be great to get this fixed asap.

Thanks
